[project]
name = "kerchunk_tools"
version = "0.1.0"
description = "Simple tools for working with kerchunk (parquet) files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastparquet>=2024.11.0",
    "kerchunk>=0.2.9",
    "pandas>=2.3.2",
    "pre-commit>=4.3.0",
    "xarray>=2025.9.0",
    "zarr>=3.1.1",
    ]
authors = [
    { name="Florian Ziemen", email="ziemen@dkrz.de" }
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
merge_datasests = "kerchunk_tools.merge_datasests:main"
remove_from_ds = "kerchunk_tools.remove_from_ds:main"
rename_dimensions = "kerchunk_tools.rename_dimensions:main"
print_ds = "kerchunk_tools.print_ds:main"
update_paths = "kerchunk_tools.update_paths:main"
